version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - cypress/install
      - cypress/run:
          name: firefox
          requires:
            - cypress/install 
          executor: cypress/browsers-chrome73-ff68
          browser: firefox
          command: npm run cypress:all
          group: firefox

      - cypress/run:
          name: chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          browser: chrome
          command: npm run cypress:all
          group: chrome
