version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
build:
  steps:
    - run:
        name: Prepare
        command: npm install
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          name: firefox
          requires:
            - cypress/install 
          executor: cypress/browsers-chrome73-ff68
          browser: firefox
          command: npm run cypress:all
          group: firefox

      - cypress/run:
          name: chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          browser: chrome
          command: npm run cypress:all
          group: chrome
